import base64
from aws_kinesis_agg.deaggregator import deaggregate_records


def kda_response_formatter(recordId, processed_payload):
    """
    helper function that formats the processed records according to Firehose object response model.

    Payload is first encoded to convert it to bytes string. Then it is encoded with base64 since Firehose 
    requires a base64 encoded object in response. This base64 encoded string is further decoded to convert it
    to string object which is json serilizable and retunable by lambda.

    :param record: the recordId of the record
    :param processed_payload: the processed data
    :return: dict object 
    """

    # status could be Ok, Dropped, ProcessingFailed. Chose Ok if records are processed successfully
    # choose Dropped if a record is to be dropped.
    # ProcessingFailed auto selected in case of failure.

    output_record = {
        'recordId': recordId,
        'result': 'Ok',
        'data': processed_payload
    }
    return output_record


def lambda_handler(event, context):
    """
    lambda handler reads records ingested into the kinesis data analytics application. 
    Incase of Kinesis Datastreams, records are aggregated so are manually deaggregated. 

    records are recieved as base64 encoded string. Decoding them returns a bytes string
    which is further decoded to get the actual string object

    :param event:  the event object generated by the service invoked
    :param context: This object provides methods and properties that provide information about the invocation, function\
    and execution environment.
    :return: none
    """

    output = []
    raw_kinesis_records = event['records']

    for record in raw_kinesis_records:
        recordId = record['recordId']
        deaggregated_records = deaggregate_records(record)
        decoded_data = []
        for record in deaggregated_records:
            data = base64.b64decode(record['kinesis']['data']).decode('utf-8')
            decoded_data.append(data)

        # all the decoded records are converted into a string that is sent back to KDA application
        # join like this "".join(decoded_data) only if records already have a \n as records delimiter,
        # otherwise do "\n".join(decoded_data)

        output_data = "".join(decoded_data)

        output_data_base64 = base64.b64encode(output_data.encode('utf-8'))
        output_data_str = output_data_base64.decode('utf-8')

        output_record = kda_response_formatter(recordId, output_data_str)
        output.append(output_record)

    print('Successfully processed {} records.'.format(len(event['records'])))
    return {'records': output}
